### ISSUE TITLE
Create a step by step process for updating a public CocoaPod like swift-wisdom

### ISSUE THREAD

**Issue by alexpersian** [IntrepidPursuits/sherpa#57]
There are multiple steps involved with updating a public facing cocoapod. This includes bumping the `.podspec` version, adding a tag to the repo, and updating the cocoapods trunk. Sherpa should document these steps for developers to use in the future.

**Comment by intrepidmatt** [comment]
@alexpersian Should this be closed with #56 ?

**Comment by alexpersian** [comment]
@intrepidmatt late, but yes I'll close this issue
